server {
    listen 80;
    server_name app.myhouse.cm;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name app.myhouse.cm;

    ssl_certificate /etc/letsencrypt/live/app.myhouse.cm/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.myhouse.cm/privkey.pem;

    root /var/www/myhouse-web;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
