MYHOUSE_UPLOAD_STORE_FILE=metertrack-upload.jks
MYHOUSE_UPLOAD_STORE_PASSWORD=R3AeIjy9h8oMH6gtViBUTvpx
MYHOUSE_UPLOAD_KEY_ALIAS=upload
MYHOUSE_UPLOAD_KEY_PASSWORD=R3AeIjy9h8oMH6gtViBUTvpx
METERTRACK_UPLOAD_STORE_FILE=metertrack-upload.jks
METERTRACK_UPLOAD_STORE_PASSWORD=R3AeIjy9h8oMH6gtViBUTvpx
METERTRACK_UPLOAD_KEY_ALIAS=upload
METERTRACK_UPLOAD_KEY_PASSWORD=R3AeIjy9h8oMH6gtViBUTvpx
