import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { Platform } from 'react-native';
import type { SQLiteDatabase } from 'expo-sqlite';
import { useDatabaseOptional, useDatabaseReady } from './DatabaseContext';

export type Language = 'fr' | 'en' | 'es';
export type ThemeMode = 'light' | 'dark';

type PreferencesContextType = {
  language: Language;
  themeMode: ThemeMode;
  needsUpgradePrompt: boolean;
  setLanguage: (lang: Language) => Promise<void>;
  setThemeMode: (mode: ThemeMode) => Promise<void>;
  resolveUpgradePrompt: (keepData: boolean) => Promise<void>;
  t: (key: string) => string;
};

const APP_VERSION = '1.0.1';

const DICT: Record<Language, Record<string, string>> = {
  fr: {
    settings: 'Parametres',
    home: 'Accueil',
    rooms: 'Chambres',
    invoices: 'Factures',
    payments: 'Paiements',
    monthConfig: 'Parametres du mois',
    language: 'Langue',
    theme: 'Theme',
    darkMode: 'Mode sombre',
    lightMode: 'Mode clair',
    about: 'A propos',
    productManager: 'Product Manager',
    contact: 'Contact',
    openMonthConfig: 'Configurer les parametres du mois',
    pickFrench: 'Francais',
    pickEnglish: 'Anglais',
    pickSpanish: 'Espagnol',
    loading: 'Chargement...',
    login: 'Se connecter',
    username: 'Identifiant',
    password: 'Mot de passe',
    enterUsername: 'Entrez votre identifiant',
    enterPassword: 'Entrez votre mot de passe',
    loginSlogan: 'Gestion locative multi-services pour l Afrique Centrale.',
    wrongCredentials: 'Identifiants incorrects.',
    forgotPassword: 'Mot de passe oublie ?',
    recoveryTitle: 'Recuperation du mot de passe',
    recoveryCode: 'Code de recuperation',
    enterRecoveryCode: 'Entrez le code de recuperation',
    newPasswordShort: 'Nouveau mot de passe',
    recoverPasswordAction: 'Reinitialiser le mot de passe',
    recoverySuccess: 'Mot de passe reinitialise. Connectez-vous avec le nouveau mot de passe.',
    recoveryFailed: 'Echec de la recuperation. Verifiez le code et le nom utilisateur.',
    sendRecoveryCode: 'Envoyer le code',
    recoveryCodeSent: 'Code envoye. Verifiez votre email.',
    recoveryCodeSentHint: 'Un code de recuperation a ete envoye a votre email.',
    recoveryCodeRequestFailed: 'Impossible d envoyer le code. Verifiez que l email de recuperation est configure.',
    recoveryEmailLabel: 'Email de recuperation',
    recoveryEmailPlaceholder: 'Ex: votreadresse@email.com',
    saveRecoveryEmail: 'Enregistrer email de recuperation',
    recoveryEmailSaved: 'Email de recuperation enregistre.',
    fillAllFields: 'Veuillez remplir tous les champs.',
    error: 'Erreur',
    success: 'Succes',
    save: 'Enregistrer',
    cancel: 'Annuler',
    indexEntry: 'Saisie des index',
    invoicesCalc: 'Calcul des factures',
    whatsappSend: 'Envoi WhatsApp',
    whatsappBroadcast: 'Diffusion WhatsApp',
    noActiveRooms: 'Aucune chambre active. Ajoutez des chambres d\'abord.',
    entered: 'Saisi',
    validate: 'Valider',
    edit: 'Modifier',
    present: 'Present',
    waterFine: 'Amende eau',
    water: 'Eau',
    electricity: 'Electricite',
    consumption: 'Conso',
    oldIndex: 'AN',
    newIndex: 'NI',
    invoicesTitle: 'Factures',
    launchCalculation: 'Lancer le calcul',
    noInvoicesCalculated: 'Aucune facture calculee. Lancez le calcul.',
    paymentTitle: 'Paiements',
    registerPayment: 'Enregistrer un paiement',
    noInvoicesFirst: 'Aucune facture. Calculez les factures d\'abord.',
    paidAmount: 'Montant paye (FCFA)',
    noteOptional: 'Observation (optionnel)',
    whatsappSendAll: 'Envoyer tout',
    whatsappResend: 'Renvoyer',
    whatsappSendOne: 'Envoyer',
    whatsappNone: 'Aucune facture a envoyer. Calculez les factures d\'abord.',
    monthParamsSaved: 'Parametres du mois enregistres.',
    monthParamsTitle: 'Parametres',
    unitPrices: 'Prix unitaires',
    meterRent: 'Location compteur',
    mainMeterSurplus: 'Surplus compteur principal',
    vatAndDeadline: 'TVA et delais',
    paymentDeadline: 'Date limite de paiement (JJ/MM/AAAA)',
    confirm: 'Confirmer',
    logout: 'Se deconnecter',
    meterTrackTitle: 'MyHouse',
    passwordMismatch: 'Les mots de passe ne correspondent pas.',
    newPasswordMin: 'Le nouveau mot de passe doit contenir au moins 6 caracteres.',
    passwordChanged: 'Mot de passe modifie avec succes.',
    oldPasswordWrong: 'Ancien mot de passe incorrect.',
    exportError: 'Erreur lors de l\'export. Verifiez que des donnees existent pour ce mois.',
    logoutTitle: 'Deconnexion',
    logoutConfirm: 'Voulez-vous vraiment vous deconnecter ?',
    disconnect: 'Deconnecter',
    monthConfigMissing: 'Parametres du mois non configures.',
    setDeadlineBeforeSend: 'Veuillez definir la date limite de paiement avant l\'envoi.',
    noInvoiceBeforeSend: 'Aucune facture calculee. Calculez les factures d\'abord.',
    invalidWhatsapp: 'Numero WhatsApp invalide',
    sendConfirmTitle: 'Confirmer l\'envoi',
    sendOpenedBody: 'Avez-vous envoye le message ?',
    cannotOpenWhatsapp: 'Impossible d\'ouvrir WhatsApp. Verifiez que WhatsApp est installe.',
    sendProcessError: 'Erreur lors de l\'envoi.',
    info: 'Info',
    allAlreadySent: 'Toutes les factures ont deja ete envoyees.',
    groupSendTitle: 'Envoi groupe',
    groupSendQuestion: 'Continuer ?',
    send: 'Envoyer',
    finished: 'Termine',
    groupSendDone: 'Envoi groupe termine. Verifiez les statuts.',
    enterMessage: 'Veuillez saisir un message.',
    noActiveResident: 'Aucun resident actif.',
    broadcastQuestion: 'Envoyer ce message',
    broadcastDone: 'Diffusion lancee.',
    cannotBroadcast: 'Impossible de lancer la diffusion WhatsApp.',
    invalidAmount: 'Veuillez saisir un montant valide.',
    paymentRecorded: 'Paiement enregistre.',
    cannotUpdateDebt: 'Impossible de mettre a jour la dette.',
    cannotSaveData: 'Impossible de sauvegarder.',
    permissionRequired: 'Permission requise',
    allowContacts: 'Autorisez l\'acces aux contacts pour selectionner un numero.',
    noPhoneForContact: 'Aucun numero trouve pour ce contact.',
    cannotOpenContacts: 'Impossible d\'ouvrir les contacts.',
    roomAlreadyExists: 'Ce numero de chambre existe deja.',
    confirmation: 'Confirmation',
    confirmAction: 'Confirmer',
    noRoomFound: 'Aucune chambre trouvee. Ajoutez-en une !',
    exportData: 'Export des donnees',
    exportResidentsXlsx: 'Exporter le fichier des residents (.xlsx)',
    exportInvoicesXlsx: 'Exporter les factures (.xlsx)',
    exportPaymentsXlsx: 'Exporter les paiements (.xlsx)',
    exportCompleteXlsx: 'Exporter le rapport mensuel complet (.xlsx)',
    changePasswordSection: 'Changer le mot de passe',
    oldPasswordLabel: 'Ancien mot de passe',
    oldPasswordPlaceholder: 'Ancien mot de passe',
    newPasswordLabel: 'Nouveau mot de passe',
    newPasswordPlaceholder: 'Nouveau mot de passe (min. 6 caracteres)',
    confirmPasswordLabel: 'Confirmer le mot de passe',
    confirmPasswordPlaceholder: 'Confirmer le mot de passe',
    changePasswordAction: 'Changer le mot de passe',
    appLabel: 'Application',
    versionLabel: 'Version',
    platformLabel: 'Plateforme',
    androidLabel: 'Android',
    webLabel: 'Web',
    desktopLabel: 'Bureau',
    emailLabel: 'Email',
    currentRole: 'Role actif',
    switchRole: 'Changer de role',
    tenantRole: 'Locataire',
    conciergeRole: 'Concierge',
    managerRole: 'Gestionnaire',
    adminCommercialRole: 'Admin commercial',
    adminSavRole: 'Admin UX / SAV',
    adminJuridiqueRole: 'Admin juridique',
    adminComptaRole: 'Admin comptabilite',
    superAdminRole: 'Super Admin',
    dashboardComplete: 'COMPLET',
    dashboardInProgress: 'EN COURS',
    roomsPendingAlert: 'chambre(s) n\'ont pas encore ete saisie(s)',
    monthConfigAlert: 'Parametres du mois non configures. Allez dans Parametres.',
    roomsIndexed: 'Chambres saisies',
    invoicesCalculatedLabel: 'Factures calculees',
    invoicesSentLabel: 'Factures envoyees',
    paymentsReceivedLabel: 'Paiements recus',
    enterIndexesBtn: 'Saisir les index',
    calculateInvoicesBtn: 'Calculer les factures',
    sendInvoicesWhatsappBtn: 'Envoyer les factures WhatsApp',
    broadcastWhatsappBtn: 'Diffuser un message WhatsApp',
    bureauWeb: 'Bureau / Web',
    occupancy: 'Occupation',
    netToRecover: 'Net a recouvrer',
    urgentContracts: 'Contrats urgents',
    criticalIncidents: 'Incidents critiques',
    complementaryOverview: 'Pilotage complementaire',
    activeContracts: 'Contrats actifs',
    openIncidents: 'Incidents ouverts',
    invoicesInError: 'Factures en erreur',
    cumulativePayments: 'Paiements cumules',
    broadcast: 'Diffusion',
    contracts: 'Contrats',
    maintenance: 'Maintenance',
    reports: 'Rapports',
    documents: 'Documents',
    dashboardLabel: 'Tableau de bord',
    sectionDashboard: 'TABLEAU DE BORD',
    sectionProperty: 'GESTION LOCATIVE',
    sectionManagement: 'GESTION',
    sectionOperations: 'EXPLOITATION',
    sectionAnalytics: 'SUIVI & ANALYTICS',
    sectionConsumption: 'CONSOMMATIONS',
    sectionFinance: 'FINANCES',
    sectionAdministration: 'ADMINISTRATION',
    portfolioLabel: 'Portefeuille',
    residentsLabel: 'Residents',
    conciergeAccounts: 'Concierges',
    conciergeAccountsDesc: 'Creation des comptes concierge et suivi des acces terrain.',
    createConciergeAccount: 'Creer un compte concierge',
    conciergeUsernameLabel: 'Identifiant concierge',
    temporaryPasswordLabel: 'Mot de passe temporaire',
    accountCreated: 'Compte cree avec succes.',
    accountExists: 'Cet identifiant existe deja.',
    createdByLabel: 'Cree par',
    pendingApprovalsTitle: 'Comptes en attente de validation',
    pendingApprovalsDesc: 'Validez ou refusez les comptes en attente pour poursuivre l activation.',
    pendingApprovalsEmpty: 'Aucun compte en attente.',
    approve: 'Approuver',
    reject: 'Refuser',
    accountApproved: 'Compte approuve.',
    accountRejected: 'Compte refuse.',
    managerPanelTitle: 'Panel gestionnaire',
    managerPanelDescription: 'Pilotage locatif, suivi du portefeuille, contrats, maintenance et rapports avec MeterTrack comme module interne.',
    managerQuickActions: 'Actions rapides',
    managerOpenMeterTrack: 'Ouvrir le module MeterTrack',
    managerBack: 'Retour au panel gestionnaire',
    managerModuleDescription: 'Accedez au noyau MeterTrack pour les index, la facturation, les paiements, la diffusion WhatsApp et les parametres du mois.',
    managerMeterTrackReadOnly: 'Vue MeterTrack',
    readOnlyAccessLabel: 'Lecture seule',
    managerReadOnlyDescription: 'Le gestionnaire supervise le noyau MeterTrack sans pouvoir modifier les index, calculs, paiements ou diffusions.',
    managerKpiOccupancyHint: 'Chambres actives avec resident principal ou facture en cours.',
    managerKpiRecoveryHint: 'Montant restant a recouvrer sur les factures du mois.',
    managerKpiContractsHint: 'Chambres a completer ou renouvellements a surveiller.',
    managerKpiIncidentsHint: 'Incidents d exploitation et actions prioritaires a traiter.',
    activeResidentsLabel: 'Residents actifs',
    configuredMonthLabel: 'Mois configure',
    readyLabel: 'Pret',
    missingLabel: 'Manquant',
    portfolioDesc: 'Vue portefeuille des chambres actives, etat de saisie et date d activation.',
    portfolioRoomSheet: 'Fiche portefeuille',
    portfolioRoomSheetDesc: 'Lecture superviseur d une chambre active, du resident, du contrat et du cycle MeterTrack.',
    activeResidentLabel: 'Resident actif',
    readingStatusLabel: 'Etat releve',
    billingStatusLabel: 'Etat facturation',
    paymentStatusLabel: 'Etat paiement',
    roomCreatedLabel: 'Date activation',
    noResidentLinked: 'Aucun resident lie',
    residentDirectory: 'Annuaire residents',
    residentDirectoryDesc: 'Residents actifs relies aux chambres, avec contact et statut.',
    contractsDesc: 'Contrats actifs, renouvellements urgents et chambres a completer.',
    contractEditorTitle: 'Fiche contrat',
    contractStartLabel: 'Date debut',
    contractEndLabel: 'Date fin',
    monthlyRentLabel: 'Loyer mensuel',
    depositLabel: 'Caution',
    contractStatusLabel: 'Statut du contrat',
    signingModeLabel: 'Mode de signature',
    autoRenewalLabel: 'Renouvellement automatique',
    notesLabel: 'Notes',
    saveContract: 'Enregistrer le contrat',
    contractSaved: 'Contrat enregistre.',
    selectRoomContractHint: 'Selectionnez une chambre pour preparer ou mettre a jour son contrat.',
    contractStatusDraft: 'Brouillon',
    contractStatusActive: 'Actif',
    contractStatusExpired: 'Expire',
    contractSigningPhysical: 'Physique',
    contractSigningDigital: 'Numerique',
    residentExternalIdLabel: 'ID resident (backend)',
    maintenanceDesc: 'Incidents d exploitation detectes sur releves, facturation, occupation et recouvrement.',
    maintenanceTicketTitle: 'Ticket maintenance',
    createMaintenanceTicket: 'Creer un ticket',
    maintenanceRoomLabel: 'Chambre concernee',
    maintenanceCategoryLabel: 'Categorie',
    maintenancePriorityLabel: 'Priorite',
    maintenanceStatusLabel: 'Statut ticket',
    maintenanceAssigneeLabel: 'Responsable',
    maintenanceSummaryLabel: 'Resume',
    maintenanceNotesLabel: 'Notes intervention',
    maintenanceSaved: 'Ticket maintenance enregistre.',
    maintenanceRoomRequired: 'La chambre et le resume du ticket sont obligatoires.',
    maintenanceApiTitle: 'Maintenance (API)',
    maintenanceApiDesc: 'Tickets synchronises avec le backend (responsabilite, couts, penalites).',
    maintenanceResponsibilityLabel: 'Responsabilite',
    estimatedCostLabel: 'Cout estime (FCFA)',
    penaltyAmountLabel: 'Montant penalite (FCFA)',
    applyPenalty: 'Appliquer la penalite',
    reportsDesc: 'Lecture direction, finance, operations et portefeuille a surveiller.',
    documentsDesc: 'Registre des contrats, pieces locatives, etats des lieux, PV et autres documents du portefeuille.',
    documentRegistryTitle: 'Registre documentaire',
    documentTypeLabel: 'Type de document',
    documentTitleLabel: 'Titre du document',
    documentStatusLabel: 'Statut du document',
    issuedOnLabel: 'Date emission',
    expiresOnLabel: 'Date expiration',
    saveDocument: 'Enregistrer le document',
    documentSaved: 'Document enregistre.',
    unsentInvoices: 'Non envoyees',
    sentInvoices: 'Envoyees',
    openWhatsapp: 'Ouvrir WhatsApp',
    markSent: 'Marquer envoyee',
    markError: 'Marquer erreur',
    noNumber: 'Aucun numero',
    stateLabel: 'Etat',
    notifications: 'Notifications',
    notificationsDesc: 'Canaux WhatsApp, email et push pour notifications critiques et rappels.',
    notificationChannelLabel: 'Canal',
    notificationRecipientLabel: 'Destinataire',
    notificationSubjectLabel: 'Sujet',
    notificationMessageLabel: 'Message',
    notificationSendAction: 'Envoyer la notification',
    notificationHistoryTitle: 'Historique notifications',
    amountLabel: 'Montant (FCFA)',
    addressLabel: 'Adresse',
    assignLabel: 'Affectation',
    exports: 'Exports',
    exportsDesc: 'Exports financiers et documents PDF pour reporting et audit.',
    marketplace: 'Marketplace',
    commonCharges: 'Charges communes',
    marketplaceDesc: 'Annonces, medias, abonnements et transactions immobilieres.',
    commonChargesDesc: 'Configurer les charges communes par residence et chambre.',
    exportMonthLabel: 'Mois d export',
    exportMeterTrackXlsx: 'Exporter MeterTrack (.xlsx)',
    exportFinanceSummaryXlsx: 'Exporter synthese finance (.xlsx)',
    exportResidentHistoryPdf: 'Exporter historique resident (PDF)',
    exportPaymentReceiptPdf: 'Exporter recu de paiement (PDF)',
    exportExitReportPdf: 'Exporter PV de sortie (PDF)',
    exportResidentIdLabel: 'ID resident',
    exportPaymentIdLabel: 'ID paiement',
    exportExitReportIdLabel: 'ID PV sortie',
    exportsTipsTitle: 'Conseils export',
    exportsTipMeterTrack: 'Le rapport MeterTrack inclut factures, paiements et index.',
    exportsTipResident: 'Utilisez l ID resident pour extraire l historique complet.',
    exportsTipPayment: 'Les recus se generent a partir de l ID paiement.',
    exportsTipExit: 'Le PV de sortie exige un ID de rapport valide.',
    balanceLabel: 'Solde',
    managementLabel: 'Direction',
    financeLabel: 'Finance',
    operationsLabel: 'Operations',
    portfolioWatchLabel: 'Portefeuille a surveiller',
    unusualConsumption: 'Consommations inhabituelles',
    avgWater: 'Conso moyenne eau',
    avgElectric: 'Conso moyenne electricite',
    noAnomaly: 'Aucune consommation inhabituelle detectee.',
    topWaterConsumers: 'Top conso eau',
    topElectricConsumers: 'Top conso electricite',
    topTotalInvoices: 'Top factures totales',
    highPriority: 'Priorite haute',
    readingsLabel: 'Releves',
    billingLabel: 'Facturation',
    unpaid: 'Impaye',
    settled: 'Solde',
    partial: 'Partiel',
    noStatus: 'Aucun statut',
    editRoomTitle: 'Modifier la chambre',
    addRoomTitle: 'Ajouter une chambre',
    roomNumberLabel: 'Numero de chambre',
    residentNameLabel: 'Nom et prenom du resident',
    whatsappNumberLabel: 'Numero WhatsApp',
    amountPaidLabel: 'Montant paye (FCFA)',
    paymentsDesc: 'Suivi des paiements, statut des factures et encaissements.',
    paymentFormTitle: 'Enregistrer un paiement',
    invoiceIdLabel: 'ID facture',
    paymentMethodLabel: 'Methode de paiement',
    paymentHistoryTitle: 'Historique des paiements',
    currentMonthSettings: 'Parametres - mois courant',
    waterUnitPriceLabel: 'PU Eau (FCFA/m3)',
    electricityUnitPriceLabel: 'PU Electricite (FCFA/kWh)',
    waterMeterRentLabel: 'LC Eau (FCFA)',
    electricityMeterRentLabel: 'LC Electricite (FCFA)',
    totalWaterSurplusLabel: 'Surplus Eau Total (FCFA)',
    totalElectricitySurplusLabel: 'Surplus Electricite Total (FCFA)',
    waterFineAmountLabel: 'Amende Eau (FCFA)',
    minimumInvoiceLabel: 'Minimum Facture (FCFA)',
    vatPercentLabel: 'TVA (%)',
    debtLabel: 'Dette',
    totalInvoiceLabel: 'Total facture',
    netToPayLabel: 'Net a payer',
    paymentDelayLabel: 'Delai de paiement',
    monthSuffixRooms: 'chambre(s)',
    monthSuffixInvoices: 'facture(s)',
    roomStatusActive: 'Actif',
    roomStatusInactive: 'Inactif',
  },
  en: {
    settings: 'Settings',
    home: 'Home',
    rooms: 'Rooms',
    invoices: 'Invoices',
    payments: 'Payments',
    monthConfig: 'Monthly settings',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    about: 'About',
    productManager: 'Product Manager',
    contact: 'Contact',
    openMonthConfig: 'Configure monthly parameters',
    pickFrench: 'French',
    pickEnglish: 'English',
    pickSpanish: 'Spanish',
    loading: 'Loading...',
    login: 'Sign in',
    username: 'Username',
    password: 'Password',
    enterUsername: 'Enter your username',
    enterPassword: 'Enter your password',
    loginSlogan: 'Multi-service property management for Central Africa.',
    wrongCredentials: 'Invalid credentials.',
    forgotPassword: 'Forgot password?',
    recoveryTitle: 'Password recovery',
    recoveryCode: 'Recovery code',
    enterRecoveryCode: 'Enter recovery code',
    newPasswordShort: 'New password',
    recoverPasswordAction: 'Reset password',
    recoverySuccess: 'Password reset successfully. Sign in with the new password.',
    recoveryFailed: 'Recovery failed. Check recovery code and username.',
    sendRecoveryCode: 'Send code',
    recoveryCodeSent: 'Code sent. Check your email.',
    recoveryCodeSentHint: 'A recovery code has been sent to your email.',
    recoveryCodeRequestFailed: 'Cannot send code. Make sure recovery email is configured.',
    recoveryEmailLabel: 'Recovery email',
    recoveryEmailPlaceholder: 'Ex: youraddress@email.com',
    saveRecoveryEmail: 'Save recovery email',
    recoveryEmailSaved: 'Recovery email saved.',
    fillAllFields: 'Please fill all fields.',
    error: 'Error',
    success: 'Success',
    save: 'Save',
    cancel: 'Cancel',
    indexEntry: 'Index Entry',
    invoicesCalc: 'Invoice Calculation',
    whatsappSend: 'WhatsApp Sending',
    whatsappBroadcast: 'WhatsApp Broadcast',
    noActiveRooms: 'No active room. Add rooms first.',
    entered: 'Saved',
    validate: 'Validate',
    edit: 'Edit',
    present: 'Present',
    waterFine: 'Water fine',
    water: 'Water',
    electricity: 'Electricity',
    consumption: 'Usage',
    oldIndex: 'OI',
    newIndex: 'NI',
    invoicesTitle: 'Invoices',
    launchCalculation: 'Start Calculation',
    noInvoicesCalculated: 'No invoice calculated yet. Start calculation.',
    paymentTitle: 'Payments',
    registerPayment: 'Record payment',
    noInvoicesFirst: 'No invoices. Calculate invoices first.',
    paidAmount: 'Paid amount (FCFA)',
    noteOptional: 'Note (optional)',
    whatsappSendAll: 'Send all',
    whatsappResend: 'Resend',
    whatsappSendOne: 'Send',
    whatsappNone: 'No invoice to send. Calculate invoices first.',
    monthParamsSaved: 'Monthly parameters saved.',
    monthParamsTitle: 'Settings',
    unitPrices: 'Unit prices',
    meterRent: 'Meter rental',
    mainMeterSurplus: 'Main meter surplus',
    vatAndDeadline: 'VAT and deadline',
    paymentDeadline: 'Payment deadline (DD/MM/YYYY)',
    confirm: 'Confirm',
    logout: 'Sign out',
    meterTrackTitle: 'MyHouse',
    passwordMismatch: 'Passwords do not match.',
    newPasswordMin: 'New password must be at least 6 characters.',
    passwordChanged: 'Password changed successfully.',
    oldPasswordWrong: 'Old password is incorrect.',
    exportError: 'Export failed. Check that data exists for this month.',
    logoutTitle: 'Logout',
    logoutConfirm: 'Do you really want to log out?',
    disconnect: 'Log out',
    monthConfigMissing: 'Monthly parameters are not configured.',
    setDeadlineBeforeSend: 'Please set the payment deadline before sending.',
    noInvoiceBeforeSend: 'No invoice calculated. Calculate invoices first.',
    invalidWhatsapp: 'Invalid WhatsApp number',
    sendConfirmTitle: 'Confirm send',
    sendOpenedBody: 'Did you send the message?',
    cannotOpenWhatsapp: 'Cannot open WhatsApp. Verify WhatsApp is installed.',
    sendProcessError: 'Error during sending.',
    info: 'Info',
    allAlreadySent: 'All invoices are already sent.',
    groupSendTitle: 'Bulk send',
    groupSendQuestion: 'Continue?',
    send: 'Send',
    finished: 'Done',
    groupSendDone: 'Bulk send completed. Check statuses.',
    enterMessage: 'Please enter a message.',
    noActiveResident: 'No active resident.',
    broadcastQuestion: 'Send this message',
    broadcastDone: 'Broadcast started.',
    cannotBroadcast: 'Cannot start WhatsApp broadcast.',
    invalidAmount: 'Please enter a valid amount.',
    paymentRecorded: 'Payment recorded.',
    cannotUpdateDebt: 'Cannot update debt.',
    cannotSaveData: 'Cannot save data.',
    permissionRequired: 'Permission required',
    allowContacts: 'Allow contacts access to pick a number.',
    noPhoneForContact: 'No phone number found for this contact.',
    cannotOpenContacts: 'Cannot open contacts.',
    roomAlreadyExists: 'This room number already exists.',
    confirmation: 'Confirmation',
    confirmAction: 'Confirm',
    noRoomFound: 'No rooms found. Add one!',
    exportData: 'Data export',
    exportResidentsXlsx: 'Export the residents file (.xlsx)',
    exportInvoicesXlsx: 'Export invoices (.xlsx)',
    exportPaymentsXlsx: 'Export payments (.xlsx)',
    exportCompleteXlsx: 'Export full monthly report (.xlsx)',
    changePasswordSection: 'Change password',
    oldPasswordLabel: 'Old password',
    oldPasswordPlaceholder: 'Old password',
    newPasswordLabel: 'New password',
    newPasswordPlaceholder: 'New password (min. 6 characters)',
    confirmPasswordLabel: 'Confirm password',
    confirmPasswordPlaceholder: 'Confirm password',
    changePasswordAction: 'Change password',
    appLabel: 'Application',
    versionLabel: 'Version',
    platformLabel: 'Platform',
    androidLabel: 'Android',
    webLabel: 'Web',
    desktopLabel: 'Desktop',
    emailLabel: 'Email',
    currentRole: 'Active role',
    switchRole: 'Switch role',
    tenantRole: 'Tenant',
    conciergeRole: 'Concierge',
    managerRole: 'Manager',
    adminCommercialRole: 'Commercial admin',
    adminSavRole: 'UX / Support admin',
    adminJuridiqueRole: 'Legal admin',
    adminComptaRole: 'Accounting admin',
    superAdminRole: 'Super Admin',
    dashboardComplete: 'COMPLETE',
    dashboardInProgress: 'IN PROGRESS',
    roomsPendingAlert: 'room(s) still need index entry',
    monthConfigAlert: 'Monthly settings are not configured. Go to Settings.',
    roomsIndexed: 'Indexed rooms',
    invoicesCalculatedLabel: 'Calculated invoices',
    invoicesSentLabel: 'Sent invoices',
    paymentsReceivedLabel: 'Recorded payments',
    enterIndexesBtn: 'Enter indexes',
    calculateInvoicesBtn: 'Calculate invoices',
    sendInvoicesWhatsappBtn: 'Send WhatsApp invoices',
    broadcastWhatsappBtn: 'Broadcast WhatsApp message',
    bureauWeb: 'Desktop / Web',
    occupancy: 'Occupancy',
    netToRecover: 'Net to recover',
    urgentContracts: 'Urgent contracts',
    criticalIncidents: 'Critical incidents',
    complementaryOverview: 'Additional oversight',
    activeContracts: 'Active contracts',
    openIncidents: 'Open incidents',
    invoicesInError: 'Invoices in error',
    cumulativePayments: 'Cumulative payments',
    broadcast: 'Broadcast',
    contracts: 'Contracts',
    maintenance: 'Maintenance',
    reports: 'Reports',
    documents: 'Documents',
    dashboardLabel: 'Dashboard',
    sectionDashboard: 'DASHBOARD',
    sectionProperty: 'PROPERTY MANAGEMENT',
    sectionManagement: 'MANAGEMENT',
    sectionOperations: 'OPERATIONS',
    sectionAnalytics: 'MONITORING & ANALYTICS',
    sectionConsumption: 'CONSUMPTION',
    sectionFinance: 'FINANCE',
    sectionAdministration: 'ADMINISTRATION',
    portfolioLabel: 'Portfolio',
    residentsLabel: 'Residents',
    conciergeAccounts: 'Concierges',
    conciergeAccountsDesc: 'Create concierge accounts and supervise field access.',
    createConciergeAccount: 'Create concierge account',
    conciergeUsernameLabel: 'Concierge username',
    temporaryPasswordLabel: 'Temporary password',
    accountCreated: 'Account created successfully.',
    accountExists: 'This username already exists.',
    createdByLabel: 'Created by',
    pendingApprovalsTitle: 'Pending approvals',
    pendingApprovalsDesc: 'Approve or reject pending accounts to continue activation.',
    pendingApprovalsEmpty: 'No pending accounts.',
    approve: 'Approve',
    reject: 'Reject',
    accountApproved: 'Account approved.',
    accountRejected: 'Account rejected.',
    managerPanelTitle: 'Manager panel',
    managerPanelDescription: 'Rental oversight, portfolio follow-up, contracts, maintenance and reporting with MeterTrack as the internal module.',
    managerQuickActions: 'Quick actions',
    managerOpenMeterTrack: 'Open MeterTrack module',
    managerBack: 'Back to manager panel',
    managerModuleDescription: 'Access the MeterTrack core for indexes, billing, payments, WhatsApp delivery and monthly settings.',
    managerMeterTrackReadOnly: 'MeterTrack view',
    readOnlyAccessLabel: 'Read only',
    managerReadOnlyDescription: 'The manager monitors the MeterTrack core without editing indexes, calculations, payments or broadcasts.',
    managerKpiOccupancyHint: 'Active rooms with a linked resident or current invoice.',
    managerKpiRecoveryHint: 'Outstanding amount to recover on this month invoices.',
    managerKpiContractsHint: 'Rooms to complete or renewals that need attention.',
    managerKpiIncidentsHint: 'Operational incidents and priority actions to process.',
    activeResidentsLabel: 'Active residents',
    configuredMonthLabel: 'Configured month',
    readyLabel: 'Ready',
    missingLabel: 'Missing',
    portfolioDesc: 'Portfolio view of active rooms, entry status and activation date.',
    portfolioRoomSheet: 'Portfolio sheet',
    portfolioRoomSheetDesc: 'Supervisor view of an active room, resident, contract and MeterTrack cycle.',
    activeResidentLabel: 'Active resident',
    readingStatusLabel: 'Reading status',
    billingStatusLabel: 'Billing status',
    paymentStatusLabel: 'Payment status',
    roomCreatedLabel: 'Activation date',
    noResidentLinked: 'No linked resident',
    residentDirectory: 'Resident directory',
    residentDirectoryDesc: 'Active residents linked to rooms, with contact and status.',
    contractsDesc: 'Active contracts, urgent renewals and rooms to complete.',
    contractEditorTitle: 'Contract sheet',
    contractStartLabel: 'Start date',
    contractEndLabel: 'End date',
    monthlyRentLabel: 'Monthly rent',
    depositLabel: 'Deposit',
    contractStatusLabel: 'Contract status',
    signingModeLabel: 'Signing mode',
    autoRenewalLabel: 'Auto renewal',
    notesLabel: 'Notes',
    saveContract: 'Save contract',
    contractSaved: 'Contract saved.',
    selectRoomContractHint: 'Select a room to prepare or update its contract.',
    contractStatusDraft: 'Draft',
    contractStatusActive: 'Active',
    contractStatusExpired: 'Expired',
    contractSigningPhysical: 'Physical',
    contractSigningDigital: 'Digital',
    residentExternalIdLabel: 'Resident ID (backend)',
    maintenanceDesc: 'Operational incidents detected from readings, billing, occupancy and collections.',
    maintenanceTicketTitle: 'Maintenance ticket',
    createMaintenanceTicket: 'Create ticket',
    maintenanceRoomLabel: 'Related room',
    maintenanceCategoryLabel: 'Category',
    maintenancePriorityLabel: 'Priority',
    maintenanceStatusLabel: 'Ticket status',
    maintenanceAssigneeLabel: 'Assignee',
    maintenanceSummaryLabel: 'Summary',
    maintenanceNotesLabel: 'Intervention notes',
    maintenanceSaved: 'Maintenance ticket saved.',
    maintenanceRoomRequired: 'Room and summary are required.',
    maintenanceApiTitle: 'Maintenance (API)',
    maintenanceApiDesc: 'Tickets synced with backend (responsibility, costs, penalties).',
    maintenanceResponsibilityLabel: 'Responsibility',
    estimatedCostLabel: 'Estimated cost (FCFA)',
    penaltyAmountLabel: 'Penalty amount (FCFA)',
    applyPenalty: 'Apply penalty',
    reportsDesc: 'Management, finance, operations and watchlist reporting.',
    documentsDesc: 'Registry of contracts, rental files, inspections, minutes and other portfolio documents.',
    documentRegistryTitle: 'Document registry',
    documentTypeLabel: 'Document type',
    documentTitleLabel: 'Document title',
    documentStatusLabel: 'Document status',
    issuedOnLabel: 'Issued on',
    expiresOnLabel: 'Expires on',
    saveDocument: 'Save document',
    documentSaved: 'Document saved.',
    unsentInvoices: 'Unsent',
    sentInvoices: 'Sent',
    openWhatsapp: 'Open WhatsApp',
    markSent: 'Mark sent',
    markError: 'Mark error',
    noNumber: 'No number',
    stateLabel: 'State',
    notifications: 'Notifications',
    notificationsDesc: 'WhatsApp, email, and push channels for alerts and reminders.',
    notificationChannelLabel: 'Channel',
    notificationRecipientLabel: 'Recipient',
    notificationSubjectLabel: 'Subject',
    notificationMessageLabel: 'Message',
    notificationSendAction: 'Send notification',
    notificationHistoryTitle: 'Notification history',
    amountLabel: 'Amount (FCFA)',
    addressLabel: 'Address',
    assignLabel: 'Assignment',
    exports: 'Exports',
    exportsDesc: 'Financial exports and PDF documents for reporting.',
    marketplace: 'Marketplace',
    commonCharges: 'Common charges',
    marketplaceDesc: 'Listings, media, subscriptions, and property transactions.',
    commonChargesDesc: 'Configure shared charges by residence or room.',
    exportMonthLabel: 'Export month',
    exportMeterTrackXlsx: 'Export MeterTrack (.xlsx)',
    exportFinanceSummaryXlsx: 'Export finance summary (.xlsx)',
    exportResidentHistoryPdf: 'Export resident history (PDF)',
    exportPaymentReceiptPdf: 'Export payment receipt (PDF)',
    exportExitReportPdf: 'Export exit report (PDF)',
    exportResidentIdLabel: 'Resident ID',
    exportPaymentIdLabel: 'Payment ID',
    exportExitReportIdLabel: 'Exit report ID',
    exportsTipsTitle: 'Export tips',
    exportsTipMeterTrack: 'MeterTrack includes invoices, payments, and readings.',
    exportsTipResident: 'Use a resident ID to export full history.',
    exportsTipPayment: 'Receipts are generated from the payment ID.',
    exportsTipExit: 'Exit report requires a valid report ID.',
    balanceLabel: 'Balance',
    managementLabel: 'Management',
    financeLabel: 'Finance',
    operationsLabel: 'Operations',
    portfolioWatchLabel: 'Portfolio to monitor',
    unusualConsumption: 'Unusual consumption',
    avgWater: 'Average water usage',
    avgElectric: 'Average electricity usage',
    noAnomaly: 'No unusual consumption detected.',
    topWaterConsumers: 'Top water consumption',
    topElectricConsumers: 'Top electricity consumption',
    topTotalInvoices: 'Top total invoices',
    highPriority: 'High priority',
    readingsLabel: 'Readings',
    billingLabel: 'Billing',
    unpaid: 'Unpaid',
    settled: 'Settled',
    partial: 'Partial',
    noStatus: 'No status',
    editRoomTitle: 'Edit room',
    addRoomTitle: 'Add room',
    roomNumberLabel: 'Room number',
    residentNameLabel: 'Resident full name',
    whatsappNumberLabel: 'WhatsApp number',
    amountPaidLabel: 'Paid amount (FCFA)',
    paymentsDesc: 'Track payments, invoice status, and collections.',
    paymentFormTitle: 'Record a payment',
    invoiceIdLabel: 'Invoice ID',
    paymentMethodLabel: 'Payment method',
    paymentHistoryTitle: 'Payment history',
    currentMonthSettings: 'Settings - current month',
    waterUnitPriceLabel: 'Water unit price (FCFA/m3)',
    electricityUnitPriceLabel: 'Electricity unit price (FCFA/kWh)',
    waterMeterRentLabel: 'Water meter rent (FCFA)',
    electricityMeterRentLabel: 'Electricity meter rent (FCFA)',
    totalWaterSurplusLabel: 'Total water surplus (FCFA)',
    totalElectricitySurplusLabel: 'Total electricity surplus (FCFA)',
    waterFineAmountLabel: 'Water fine (FCFA)',
    minimumInvoiceLabel: 'Minimum invoice (FCFA)',
    vatPercentLabel: 'VAT (%)',
    debtLabel: 'Debt',
    totalInvoiceLabel: 'Invoice total',
    netToPayLabel: 'Net to pay',
    paymentDelayLabel: 'Payment deadline',
    monthSuffixRooms: 'room(s)',
    monthSuffixInvoices: 'invoice(s)',
    roomStatusActive: 'Active',
    roomStatusInactive: 'Inactive',
  },
  es: {
    settings: 'Configuracion',
    home: 'Inicio',
    rooms: 'Habitaciones',
    invoices: 'Facturas',
    payments: 'Pagos',
    monthConfig: 'Parametros del mes',
    language: 'Idioma',
    theme: 'Tema',
    darkMode: 'Modo oscuro',
    lightMode: 'Modo claro',
    about: 'Acerca de',
    productManager: 'Product Manager',
    contact: 'Contacto',
    openMonthConfig: 'Configurar los parametros del mes',
    pickFrench: 'Frances',
    pickEnglish: 'Ingles',
    pickSpanish: 'Espanol',
    loading: 'Cargando...',
    login: 'Iniciar sesion',
    username: 'Usuario',
    password: 'Contrasena',
    enterUsername: 'Ingrese su usuario',
    enterPassword: 'Ingrese su contrasena',
    loginSlogan: 'Gestion inmobiliaria multiservicio para Africa Central.',
    wrongCredentials: 'Credenciales incorrectas.',
    forgotPassword: 'Olvido su contrasena?',
    recoveryTitle: 'Recuperacion de contrasena',
    recoveryCode: 'Codigo de recuperacion',
    enterRecoveryCode: 'Ingrese el codigo de recuperacion',
    newPasswordShort: 'Nueva contrasena',
    recoverPasswordAction: 'Restablecer contrasena',
    recoverySuccess: 'Contrasena restablecida correctamente.',
    recoveryFailed: 'Fallo la recuperacion.',
    sendRecoveryCode: 'Enviar codigo',
    recoveryCodeSent: 'Codigo enviado.',
    recoveryCodeSentHint: 'Se envio un codigo a su correo.',
    recoveryCodeRequestFailed: 'No se puede enviar el codigo.',
    recoveryEmailLabel: 'Correo de recuperacion',
    recoveryEmailPlaceholder: 'Ej: correo@dominio.com',
    saveRecoveryEmail: 'Guardar correo de recuperacion',
    recoveryEmailSaved: 'Correo de recuperacion guardado.',
    fillAllFields: 'Complete todos los campos.',
    error: 'Error',
    success: 'Exito',
    save: 'Guardar',
    cancel: 'Cancelar',
    indexEntry: 'Captura de indices',
    invoicesCalc: 'Calculo de facturas',
    whatsappSend: 'Envio por WhatsApp',
    whatsappBroadcast: 'Difusion por WhatsApp',
    noActiveRooms: 'No hay habitaciones activas.',
    entered: 'Guardado',
    validate: 'Validar',
    edit: 'Editar',
    present: 'Presente',
    waterFine: 'Multa de agua',
    water: 'Agua',
    electricity: 'Electricidad',
    consumption: 'Consumo',
    oldIndex: 'AI',
    newIndex: 'NI',
    invoicesTitle: 'Facturas',
    launchCalculation: 'Lanzar calculo',
    noInvoicesCalculated: 'No hay facturas calculadas.',
    paymentTitle: 'Pagos',
    registerPayment: 'Registrar un pago',
    noInvoicesFirst: 'No hay facturas.',
    paidAmount: 'Monto pagado (FCFA)',
    noteOptional: 'Observacion (opcional)',
    whatsappSendAll: 'Enviar todo',
    whatsappResend: 'Reenviar',
    whatsappSendOne: 'Enviar',
    whatsappNone: 'No hay facturas para enviar.',
    monthParamsSaved: 'Parametros del mes guardados.',
    monthParamsTitle: 'Parametros',
    unitPrices: 'Precios unitarios',
    meterRent: 'Alquiler del contador',
    mainMeterSurplus: 'Excedente contador principal',
    vatAndDeadline: 'IVA y plazos',
    paymentDeadline: 'Fecha limite de pago (DD/MM/AAAA)',
    confirm: 'Confirmar',
    logout: 'Cerrar sesion',
    meterTrackTitle: 'MyHouse',
    passwordMismatch: 'Las contrasenas no coinciden.',
    newPasswordMin: 'La nueva contrasena debe tener al menos 6 caracteres.',
    passwordChanged: 'Contrasena cambiada con exito.',
    oldPasswordWrong: 'La contrasena antigua es incorrecta.',
    exportError: 'Error durante la exportacion.',
    logoutTitle: 'Cerrar sesion',
    logoutConfirm: 'Desea cerrar sesion?',
    disconnect: 'Salir',
    monthConfigMissing: 'Los parametros del mes no estan configurados.',
    setDeadlineBeforeSend: 'Defina la fecha limite de pago antes del envio.',
    noInvoiceBeforeSend: 'No hay facturas calculadas.',
    invalidWhatsapp: 'Numero de WhatsApp invalido',
    sendConfirmTitle: 'Confirmar envio',
    sendOpenedBody: 'Envio el mensaje?',
    cannotOpenWhatsapp: 'No se puede abrir WhatsApp.',
    sendProcessError: 'Error durante el envio.',
    info: 'Info',
    allAlreadySent: 'Todas las facturas ya fueron enviadas.',
    groupSendTitle: 'Envio masivo',
    groupSendQuestion: 'Continuar?',
    send: 'Enviar',
    finished: 'Terminado',
    groupSendDone: 'Envio masivo terminado.',
    enterMessage: 'Ingrese un mensaje.',
    noActiveResident: 'No hay residente activo.',
    broadcastQuestion: 'Enviar este mensaje',
    broadcastDone: 'Difusion iniciada.',
    cannotBroadcast: 'No se puede iniciar la difusion.',
    invalidAmount: 'Ingrese un monto valido.',
    paymentRecorded: 'Pago registrado.',
    cannotUpdateDebt: 'No se puede actualizar la deuda.',
    cannotSaveData: 'No se puede guardar.',
    permissionRequired: 'Permiso requerido',
    allowContacts: 'Permita el acceso a contactos.',
    noPhoneForContact: 'No se encontro numero.',
    cannotOpenContacts: 'No se pueden abrir los contactos.',
    roomAlreadyExists: 'Este numero de habitacion ya existe.',
    confirmation: 'Confirmacion',
    confirmAction: 'Confirmar',
    noRoomFound: 'No se encontro ninguna habitacion.',
    exportData: 'Exportacion de datos',
    exportResidentsXlsx: 'Exportar residentes (.xlsx)',
    exportInvoicesXlsx: 'Exportar facturas (.xlsx)',
    exportPaymentsXlsx: 'Exportar pagos (.xlsx)',
    exportCompleteXlsx: 'Exportar reporte mensual completo (.xlsx)',
    changePasswordSection: 'Cambiar contrasena',
    oldPasswordLabel: 'Contrasena antigua',
    oldPasswordPlaceholder: 'Contrasena antigua',
    newPasswordLabel: 'Nueva contrasena',
    newPasswordPlaceholder: 'Nueva contrasena (min. 6 caracteres)',
    confirmPasswordLabel: 'Confirmar contrasena',
    confirmPasswordPlaceholder: 'Confirmar contrasena',
    changePasswordAction: 'Cambiar contrasena',
    appLabel: 'Aplicacion',
    versionLabel: 'Version',
    platformLabel: 'Plataforma',
    androidLabel: 'Android',
    webLabel: 'Web',
    desktopLabel: 'Escritorio',
    emailLabel: 'Correo',
    currentRole: 'Rol activo',
    switchRole: 'Cambiar rol',
    tenantRole: 'Inquilino',
    conciergeRole: 'Conserje',
    managerRole: 'Gestor',
    adminCommercialRole: 'Admin comercial',
    adminSavRole: 'Admin soporte',
    adminJuridiqueRole: 'Admin legal',
    adminComptaRole: 'Admin contable',
    superAdminRole: 'Super Admin',
    dashboardComplete: 'COMPLETO',
    dashboardInProgress: 'EN CURSO',
    roomsPendingAlert: 'habitacion(es) aun pendientes',
    monthConfigAlert: 'Los parametros del mes no estan configurados.',
    roomsIndexed: 'Habitaciones registradas',
    invoicesCalculatedLabel: 'Facturas calculadas',
    invoicesSentLabel: 'Facturas enviadas',
    paymentsReceivedLabel: 'Pagos registrados',
    enterIndexesBtn: 'Capturar indices',
    calculateInvoicesBtn: 'Calcular facturas',
    sendInvoicesWhatsappBtn: 'Enviar facturas por WhatsApp',
    broadcastWhatsappBtn: 'Difundir mensaje por WhatsApp',
    bureauWeb: 'Escritorio / Web',
    occupancy: 'Ocupacion',
    netToRecover: 'Neto por recuperar',
    urgentContracts: 'Contratos urgentes',
    criticalIncidents: 'Incidentes criticos',
    complementaryOverview: 'Supervision complementaria',
    activeContracts: 'Contratos activos',
    openIncidents: 'Incidentes abiertos',
    invoicesInError: 'Facturas con error',
    cumulativePayments: 'Pagos acumulados',
    broadcast: 'Difusion',
    contracts: 'Contratos',
    maintenance: 'Mantenimiento',
    reports: 'Reportes',
    documents: 'Documentos',
    dashboardLabel: 'Panel',
    sectionDashboard: 'TABLERO',
    sectionProperty: 'GESTION LOCATIVA',
    sectionManagement: 'GESTION',
    sectionOperations: 'OPERACIONES',
    sectionAnalytics: 'SEGUIMIENTO & ANALITICA',
    sectionConsumption: 'CONSUMOS',
    sectionFinance: 'FINANZAS',
    sectionAdministration: 'ADMINISTRACION',
    portfolioLabel: 'Portafolio',
    residentsLabel: 'Residentes',
    conciergeAccounts: 'Conserjes',
    conciergeAccountsDesc: 'Creacion de cuentas concierge y seguimiento de accesos de campo.',
    createConciergeAccount: 'Crear cuenta concierge',
    conciergeUsernameLabel: 'Usuario concierge',
    temporaryPasswordLabel: 'Contrasena temporal',
    accountCreated: 'Cuenta creada con exito.',
    accountExists: 'Este usuario ya existe.',
    createdByLabel: 'Creado por',
    pendingApprovalsTitle: 'Cuentas pendientes',
    pendingApprovalsDesc: 'Apruebe o rechace cuentas pendientes para continuar la activacion.',
    pendingApprovalsEmpty: 'No hay cuentas pendientes.',
    approve: 'Aprobar',
    reject: 'Rechazar',
    accountApproved: 'Cuenta aprobada.',
    accountRejected: 'Cuenta rechazada.',
    managerPanelTitle: 'Panel del gestor',
    managerPanelDescription: 'Pilotaje locativo, seguimiento del portafolio, contratos, mantenimiento y reportes con MeterTrack como modulo interno.',
    managerQuickActions: 'Acciones rapidas',
    managerOpenMeterTrack: 'Abrir modulo MeterTrack',
    managerBack: 'Volver al panel del gestor',
    managerModuleDescription: 'Acceda al nucleo MeterTrack para indices, facturacion, pagos, difusion por WhatsApp y parametros mensuales.',
    managerMeterTrackReadOnly: 'Vista MeterTrack',
    readOnlyAccessLabel: 'Solo lectura',
    managerReadOnlyDescription: 'El gestor supervisa el nucleo MeterTrack sin modificar indices, calculos, pagos ni difusiones.',
    managerKpiOccupancyHint: 'Habitaciones activas con residente vinculado o factura actual.',
    managerKpiRecoveryHint: 'Monto restante por recuperar en las facturas del mes.',
    managerKpiContractsHint: 'Habitaciones por completar o renovaciones a vigilar.',
    managerKpiIncidentsHint: 'Incidentes operativos y acciones prioritarias por tratar.',
    activeResidentsLabel: 'Residentes activos',
    configuredMonthLabel: 'Mes configurado',
    readyLabel: 'Listo',
    missingLabel: 'Faltante',
    portfolioDesc: 'Vista del portafolio de habitaciones activas, estado de captura y fecha de activacion.',
    portfolioRoomSheet: 'Ficha portafolio',
    portfolioRoomSheetDesc: 'Vista de supervision de una habitacion activa, del residente, del contrato y del ciclo MeterTrack.',
    activeResidentLabel: 'Residente activo',
    readingStatusLabel: 'Estado lectura',
    billingStatusLabel: 'Estado facturacion',
    paymentStatusLabel: 'Estado pago',
    roomCreatedLabel: 'Fecha activacion',
    noResidentLinked: 'Sin residente vinculado',
    residentDirectory: 'Directorio de residentes',
    residentDirectoryDesc: 'Residentes activos vinculados a habitaciones, con contacto y estado.',
    contractsDesc: 'Contratos activos, renovaciones urgentes y habitaciones por completar.',
    contractEditorTitle: 'Ficha contrato',
    contractStartLabel: 'Fecha inicio',
    contractEndLabel: 'Fecha fin',
    monthlyRentLabel: 'Alquiler mensual',
    depositLabel: 'Deposito',
    contractStatusLabel: 'Estado del contrato',
    signingModeLabel: 'Modo de firma',
    autoRenewalLabel: 'Renovacion automatica',
    notesLabel: 'Notas',
    saveContract: 'Guardar contrato',
    contractSaved: 'Contrato guardado.',
    selectRoomContractHint: 'Seleccione una habitacion para preparar o actualizar su contrato.',
    contractStatusDraft: 'Borrador',
    contractStatusActive: 'Activo',
    contractStatusExpired: 'Vencido',
    contractSigningPhysical: 'Fisica',
    contractSigningDigital: 'Digital',
    residentExternalIdLabel: 'ID de residente (backend)',
    maintenanceDesc: 'Incidentes operativos detectados en lecturas, facturacion, ocupacion y cobro.',
    maintenanceTicketTitle: 'Ticket de mantenimiento',
    createMaintenanceTicket: 'Crear ticket',
    maintenanceRoomLabel: 'Habitacion relacionada',
    maintenanceCategoryLabel: 'Categoria',
    maintenancePriorityLabel: 'Prioridad',
    maintenanceStatusLabel: 'Estado del ticket',
    maintenanceAssigneeLabel: 'Responsable',
    maintenanceSummaryLabel: 'Resumen',
    maintenanceNotesLabel: 'Notas de intervencion',
    maintenanceSaved: 'Ticket de mantenimiento guardado.',
    maintenanceRoomRequired: 'La habitacion y el resumen son obligatorios.',
    maintenanceApiTitle: 'Mantenimiento (API)',
    maintenanceApiDesc: 'Tickets sincronizados con el backend (responsabilidad, costos, penalizaciones).',
    maintenanceResponsibilityLabel: 'Responsabilidad',
    estimatedCostLabel: 'Costo estimado (FCFA)',
    penaltyAmountLabel: 'Monto de penalizacion (FCFA)',
    applyPenalty: 'Aplicar penalizacion',
    reportsDesc: 'Lectura de direccion, finanzas, operaciones y portafolio a vigilar.',
    documentsDesc: 'Registro de contratos, piezas locativas, estados de entrada, actas y otros documentos del portafolio.',
    documentRegistryTitle: 'Registro documental',
    documentTypeLabel: 'Tipo de documento',
    documentTitleLabel: 'Titulo del documento',
    documentStatusLabel: 'Estado del documento',
    issuedOnLabel: 'Fecha emision',
    expiresOnLabel: 'Fecha expiracion',
    saveDocument: 'Guardar documento',
    documentSaved: 'Documento guardado.',
    unsentInvoices: 'No enviadas',
    sentInvoices: 'Enviadas',
    openWhatsapp: 'Abrir WhatsApp',
    markSent: 'Marcar enviada',
    markError: 'Marcar error',
    noNumber: 'Sin numero',
    stateLabel: 'Estado',
    notifications: 'Notificaciones',
    notificationsDesc: 'Canales WhatsApp, email y push para alertas y recordatorios.',
    notificationChannelLabel: 'Canal',
    notificationRecipientLabel: 'Destinatario',
    notificationSubjectLabel: 'Asunto',
    notificationMessageLabel: 'Mensaje',
    notificationSendAction: 'Enviar notificacion',
    notificationHistoryTitle: 'Historial de notificaciones',
    amountLabel: 'Monto (FCFA)',
    addressLabel: 'Direccion',
    assignLabel: 'Asignacion',
    exports: 'Exportaciones',
    exportsDesc: 'Exportes financieros y documentos PDF para reportes.',
    marketplace: 'Marketplace',
    commonCharges: 'Cargos comunes',
    marketplaceDesc: 'Anuncios, medios, suscripciones y transacciones inmobiliarias.',
    commonChargesDesc: 'Configurar cargos comunes por residencia o habitacion.',
    exportMonthLabel: 'Mes de exportacion',
    exportMeterTrackXlsx: 'Exportar MeterTrack (.xlsx)',
    exportFinanceSummaryXlsx: 'Exportar resumen financiero (.xlsx)',
    exportResidentHistoryPdf: 'Exportar historial de residente (PDF)',
    exportPaymentReceiptPdf: 'Exportar recibo de pago (PDF)',
    exportExitReportPdf: 'Exportar acta de salida (PDF)',
    exportResidentIdLabel: 'ID de residente',
    exportPaymentIdLabel: 'ID de pago',
    exportExitReportIdLabel: 'ID de acta de salida',
    exportsTipsTitle: 'Consejos de exportacion',
    exportsTipMeterTrack: 'MeterTrack incluye facturas, pagos y lecturas.',
    exportsTipResident: 'Use el ID de residente para exportar el historial completo.',
    exportsTipPayment: 'Los recibos se generan con el ID de pago.',
    exportsTipExit: 'El acta de salida requiere un ID valido.',
    balanceLabel: 'Saldo',
    managementLabel: 'Direccion',
    financeLabel: 'Finanzas',
    operationsLabel: 'Operaciones',
    portfolioWatchLabel: 'Portafolio a vigilar',
    unusualConsumption: 'Consumo inusual',
    avgWater: 'Consumo promedio agua',
    avgElectric: 'Consumo promedio electricidad',
    noAnomaly: 'No se detecto consumo inusual.',
    topWaterConsumers: 'Top consumo agua',
    topElectricConsumers: 'Top consumo electricidad',
    topTotalInvoices: 'Top facturas totales',
    highPriority: 'Alta prioridad',
    readingsLabel: 'Lecturas',
    billingLabel: 'Facturacion',
    unpaid: 'Impaga',
    settled: 'Saldada',
    partial: 'Parcial',
    noStatus: 'Sin estado',
    editRoomTitle: 'Modificar habitacion',
    addRoomTitle: 'Agregar habitacion',
    roomNumberLabel: 'Numero de habitacion',
    residentNameLabel: 'Nombre y apellido del residente',
    whatsappNumberLabel: 'Numero de WhatsApp',
    amountPaidLabel: 'Monto pagado (FCFA)',
    paymentsDesc: 'Seguimiento de pagos, estado de facturas y cobros.',
    paymentFormTitle: 'Registrar un pago',
    invoiceIdLabel: 'ID de factura',
    paymentMethodLabel: 'Metodo de pago',
    paymentHistoryTitle: 'Historial de pagos',
    currentMonthSettings: 'Parametros - mes actual',
    waterUnitPriceLabel: 'PU Agua (FCFA/m3)',
    electricityUnitPriceLabel: 'PU Electricidad (FCFA/kWh)',
    waterMeterRentLabel: 'LC Agua (FCFA)',
    electricityMeterRentLabel: 'LC Electricidad (FCFA)',
    totalWaterSurplusLabel: 'Excedente total agua (FCFA)',
    totalElectricitySurplusLabel: 'Excedente total electricidad (FCFA)',
    waterFineAmountLabel: 'Multa de agua (FCFA)',
    minimumInvoiceLabel: 'Factura minima (FCFA)',
    vatPercentLabel: 'IVA (%)',
    debtLabel: 'Deuda',
    totalInvoiceLabel: 'Factura total',
    netToPayLabel: 'Neto a pagar',
    paymentDelayLabel: 'Fecha limite de pago',
    monthSuffixRooms: 'habitacion(es)',
    monthSuffixInvoices: 'factura(s)',
    roomStatusActive: 'Activa',
    roomStatusInactive: 'Inactiva',
  },
};

const ColorsByTheme = {
  light: {
    primary: '#1A3C5E',
    secondary: '#DC9414',
    background: '#F6F8FB',
    text: '#132235',
    textLight: '#6B7280',
    white: '#FFFFFF',
    success: '#1E9952',
    error: '#C82333',
    warning: '#D06800',
    border: '#D5DCE4',
    cardBg: '#FFFFFF',
    inputBg: '#F8FAFC',
    disabled: '#9CA3AF',
    tabBg: '#FFFFFF',
  },
  dark: {
    primary: '#214B86',
    secondary: '#18B8B0',
    background: '#121A24',
    text: '#F8FAFC',
    textLight: '#A7B2C2',
    white: '#FFFFFF',
    success: '#2FB34A',
    error: '#FF5A5F',
    warning: '#F2A93B',
    border: '#3A4655',
    cardBg: '#27303F',
    inputBg: '#131B28',
    disabled: '#8792A3',
    tabBg: '#101720',
  },
} as const;

const PreferencesContext = createContext<PreferencesContextType | null>(null);

async function getSetting(db: SQLiteDatabase, key: string): Promise<string | null> {
  const row = await db.getFirstAsync<{ value: string }>('SELECT value FROM app_settings WHERE key = ?', [key]);
  return row?.value ?? null;
}

async function setSetting(db: SQLiteDatabase, key: string, value: string): Promise<void> {
  await db.runAsync('INSERT OR REPLACE INTO app_settings (key, value) VALUES (?, ?)', [key, value]);
}

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const db = useDatabaseOptional();
  const ready = useDatabaseReady();
  const [language, setLanguageState] = useState<Language>('fr');
  const [themeMode, setThemeModeState] = useState<ThemeMode>('light');
  const [needsUpgradePrompt, setNeedsUpgradePrompt] = useState(false);

  const canUseBrowserStorage = Platform.OS === 'web';

  const getBrowserSetting = (key: string): string | null => {
    if (!canUseBrowserStorage || typeof window === 'undefined' || !window.localStorage) return null;
    return window.localStorage.getItem(`myhouse:${key}`);
  };

  const setBrowserSetting = (key: string, value: string): void => {
    if (!canUseBrowserStorage || typeof window === 'undefined' || !window.localStorage) return;
    window.localStorage.setItem(`myhouse:${key}`, value);
  };

  useEffect(() => {
    async function load() {
      if (!ready) return;
      const lang = db ? await getSetting(db, 'language') : getBrowserSetting('language');
      const mode = db ? await getSetting(db, 'theme_mode') : getBrowserSetting('theme_mode');
      const installedVersion = db ? await getSetting(db, 'app_version') : getBrowserSetting('app_version');
      if (lang === 'fr' || lang === 'en' || lang === 'es') setLanguageState(lang);
      if (mode === 'light' || mode === 'dark') setThemeModeState(mode);
      if (!db) {
        if (installedVersion !== APP_VERSION) {
          setBrowserSetting('app_version', APP_VERSION);
        }
        setNeedsUpgradePrompt(false);
        return;
      }
      if (installedVersion !== APP_VERSION) {
        setNeedsUpgradePrompt(true);
      }
    }
    load();
  }, [db, ready]);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    if (!db) {
      setBrowserSetting('language', lang);
      return;
    }
    await setSetting(db, 'language', lang);
  };

  const setThemeMode = async (mode: ThemeMode) => {
    setThemeModeState(mode);
    if (!db) {
      setBrowserSetting('theme_mode', mode);
      return;
    }
    await setSetting(db, 'theme_mode', mode);
  };

  const resolveUpgradePrompt = async (keepData: boolean) => {
    if (!db) {
      if (!keepData && canUseBrowserStorage && typeof window !== 'undefined' && window.localStorage) {
        window.localStorage.removeItem('myhouse:console-demo');
      }
      setBrowserSetting('app_version', APP_VERSION);
      setNeedsUpgradePrompt(false);
      return;
    }
    if (!keepData) {
      await db.execAsync(`
        DELETE FROM payments;
        DELETE FROM invoices;
        DELETE FROM index_readings;
        DELETE FROM month_config;
        DELETE FROM rooms;
      `);
    }
    await setSetting(db, 'app_version', APP_VERSION);
    setNeedsUpgradePrompt(false);
  };

  const t = (key: string): string => DICT[language][key] ?? key;

  const value = useMemo(
    () => ({
      language,
      themeMode,
      needsUpgradePrompt,
      setLanguage,
      setThemeMode,
      resolveUpgradePrompt,
      t,
    }),
    [language, themeMode, needsUpgradePrompt]
  );

  return (
    <PreferencesContext.Provider value={value}>
      {children}
    </PreferencesContext.Provider>
  );
}

export function usePreferences() {
  const ctx = useContext(PreferencesContext);
  if (!ctx) throw new Error('PreferencesProvider missing');
  return ctx;
}

export function useThemeColors() {
  const { themeMode } = usePreferences();
  return ColorsByTheme[themeMode];
}
